#pragma once

namespace dat
{
	enum Mods
	{
		MOD_SHIFT = GLFW_MOD_SHIFT,
		MOD_CTRL = GLFW_MOD_CONTROL,
		MOD_ALT = GLFW_MOD_ALT,
		MOD_SUPER = GLFW_MOD_SUPER,
		MOD_CAPS_LOCK = GLFW_MOD_CAPS_LOCK,
		MOD_NUM_LOCK = GLFW_MOD_NUM_LOCK,
	};
}