#pragma once
#include "pch.h"
#include "../IEvent.h"

namespace dat
{
	enum KeyAction
	{
		KEY_RELEASE = GLFW_RELEASE,
		KEY_PRESS = GLFW_PRESS,
		KEY_REPEAT = GLFW_REPEAT
	};

	class KeyButtonEvent : public IEvent
	{
	public:
		KeyButtonEvent(int key, KeyAction action, int mods, EventType type = EventType::KEY_BUTTON_EVENT)
			: IEvent(type), key(key), action(action), mods(mods)
		{

		}

		STATIC_EVENT_TYPE(KEY_BUTTON_EVENT)

	public:
		KeyAction action;
		int key, mods;
	};

#ifdef DAT_DEBUG

	#define TRANSLATE_KEY(keyMacro) if (key == keyMacro) return #keyMacro

	inline std::string debugKeyName(int key) 
	{
		TRANSLATE_KEY(GLFW_KEY_UNKNOWN);
		TRANSLATE_KEY(GLFW_KEY_SPACE);
		TRANSLATE_KEY(GLFW_KEY_APOSTROPHE);
		TRANSLATE_KEY(GLFW_KEY_COMMA);
		TRANSLATE_KEY(GLFW_KEY_MINUS);
		TRANSLATE_KEY(GLFW_KEY_PERIOD);
		TRANSLATE_KEY(GLFW_KEY_SLASH);
		TRANSLATE_KEY(GLFW_KEY_0);
		TRANSLATE_KEY(GLFW_KEY_1);
		TRANSLATE_KEY(GLFW_KEY_2);
		TRANSLATE_KEY(GLFW_KEY_3);
		TRANSLATE_KEY(GLFW_KEY_4);
		TRANSLATE_KEY(GLFW_KEY_5);
		TRANSLATE_KEY(GLFW_KEY_6);
		TRANSLATE_KEY(GLFW_KEY_7);
		TRANSLATE_KEY(GLFW_KEY_8);
		TRANSLATE_KEY(GLFW_KEY_9);
		TRANSLATE_KEY(GLFW_KEY_SEMICOLON);
		TRANSLATE_KEY(GLFW_KEY_EQUAL);
		TRANSLATE_KEY(GLFW_KEY_A);
		TRANSLATE_KEY(GLFW_KEY_B);
		TRANSLATE_KEY(GLFW_KEY_C);
		TRANSLATE_KEY(GLFW_KEY_D);
		TRANSLATE_KEY(GLFW_KEY_E);
		TRANSLATE_KEY(GLFW_KEY_F);
		TRANSLATE_KEY(GLFW_KEY_G);
		TRANSLATE_KEY(GLFW_KEY_H);
		TRANSLATE_KEY(GLFW_KEY_I);
		TRANSLATE_KEY(GLFW_KEY_J);
		TRANSLATE_KEY(GLFW_KEY_K);
		TRANSLATE_KEY(GLFW_KEY_L);
		TRANSLATE_KEY(GLFW_KEY_M);
		TRANSLATE_KEY(GLFW_KEY_N);
		TRANSLATE_KEY(GLFW_KEY_O);
		TRANSLATE_KEY(GLFW_KEY_P);
		TRANSLATE_KEY(GLFW_KEY_Q);
		TRANSLATE_KEY(GLFW_KEY_R);
		TRANSLATE_KEY(GLFW_KEY_S);
		TRANSLATE_KEY(GLFW_KEY_T);
		TRANSLATE_KEY(GLFW_KEY_U);
		TRANSLATE_KEY(GLFW_KEY_V);
		TRANSLATE_KEY(GLFW_KEY_W);
		TRANSLATE_KEY(GLFW_KEY_X);
		TRANSLATE_KEY(GLFW_KEY_Y);
		TRANSLATE_KEY(GLFW_KEY_Z);
		TRANSLATE_KEY(GLFW_KEY_LEFT_BRACKET);
		TRANSLATE_KEY(GLFW_KEY_BACKSLASH);
		TRANSLATE_KEY(GLFW_KEY_RIGHT_BRACKET);
		TRANSLATE_KEY(GLFW_KEY_GRAVE_ACCENT);
		TRANSLATE_KEY(GLFW_KEY_WORLD_1);
		TRANSLATE_KEY(GLFW_KEY_WORLD_2);
		TRANSLATE_KEY(GLFW_KEY_ESCAPE);
		TRANSLATE_KEY(GLFW_KEY_ENTER);
		TRANSLATE_KEY(GLFW_KEY_TAB);
		TRANSLATE_KEY(GLFW_KEY_BACKSPACE);
		TRANSLATE_KEY(GLFW_KEY_INSERT);
		TRANSLATE_KEY(GLFW_KEY_DELETE);
		TRANSLATE_KEY(GLFW_KEY_RIGHT);
		TRANSLATE_KEY(GLFW_KEY_LEFT);
		TRANSLATE_KEY(GLFW_KEY_DOWN);
		TRANSLATE_KEY(GLFW_KEY_UP);
		TRANSLATE_KEY(GLFW_KEY_PAGE_UP);
		TRANSLATE_KEY(GLFW_KEY_PAGE_DOWN);
		TRANSLATE_KEY(GLFW_KEY_HOME);
		TRANSLATE_KEY(GLFW_KEY_END);
		TRANSLATE_KEY(GLFW_KEY_CAPS_LOCK);
		TRANSLATE_KEY(GLFW_KEY_SCROLL_LOCK);
		TRANSLATE_KEY(GLFW_KEY_NUM_LOCK);
		TRANSLATE_KEY(GLFW_KEY_PRINT_SCREEN);
		TRANSLATE_KEY(GLFW_KEY_PAUSE);
		TRANSLATE_KEY(GLFW_KEY_F1);
		TRANSLATE_KEY(GLFW_KEY_F2);
		TRANSLATE_KEY(GLFW_KEY_F3);
		TRANSLATE_KEY(GLFW_KEY_F4);
		TRANSLATE_KEY(GLFW_KEY_F5);
		TRANSLATE_KEY(GLFW_KEY_F6);
		TRANSLATE_KEY(GLFW_KEY_F7);
		TRANSLATE_KEY(GLFW_KEY_F8);
		TRANSLATE_KEY(GLFW_KEY_F9);
		TRANSLATE_KEY(GLFW_KEY_F10);
		TRANSLATE_KEY(GLFW_KEY_F11);
		TRANSLATE_KEY(GLFW_KEY_F12);
		TRANSLATE_KEY(GLFW_KEY_F13);
		TRANSLATE_KEY(GLFW_KEY_F14);
		TRANSLATE_KEY(GLFW_KEY_F15);
		TRANSLATE_KEY(GLFW_KEY_F16);
		TRANSLATE_KEY(GLFW_KEY_F17);
		TRANSLATE_KEY(GLFW_KEY_F18);
		TRANSLATE_KEY(GLFW_KEY_F19);
		TRANSLATE_KEY(GLFW_KEY_F20);
		TRANSLATE_KEY(GLFW_KEY_F21);
		TRANSLATE_KEY(GLFW_KEY_F22);
		TRANSLATE_KEY(GLFW_KEY_F23);
		TRANSLATE_KEY(GLFW_KEY_F24);
		TRANSLATE_KEY(GLFW_KEY_F25);
		TRANSLATE_KEY(GLFW_KEY_KP_0);
		TRANSLATE_KEY(GLFW_KEY_KP_1);
		TRANSLATE_KEY(GLFW_KEY_KP_2);
		TRANSLATE_KEY(GLFW_KEY_KP_3);
		TRANSLATE_KEY(GLFW_KEY_KP_4);
		TRANSLATE_KEY(GLFW_KEY_KP_5);
		TRANSLATE_KEY(GLFW_KEY_KP_6);
		TRANSLATE_KEY(GLFW_KEY_KP_7);
		TRANSLATE_KEY(GLFW_KEY_KP_8);
		TRANSLATE_KEY(GLFW_KEY_KP_9);
		TRANSLATE_KEY(GLFW_KEY_KP_DECIMAL);
		TRANSLATE_KEY(GLFW_KEY_KP_DIVIDE);
		TRANSLATE_KEY(GLFW_KEY_KP_MULTIPLY);
		TRANSLATE_KEY(GLFW_KEY_KP_SUBTRACT);
		TRANSLATE_KEY(GLFW_KEY_KP_ADD);
		TRANSLATE_KEY(GLFW_KEY_KP_ENTER);
		TRANSLATE_KEY(GLFW_KEY_KP_EQUAL);
		TRANSLATE_KEY(GLFW_KEY_LEFT_SHIFT);
		TRANSLATE_KEY(GLFW_KEY_LEFT_CONTROL);
		TRANSLATE_KEY(GLFW_KEY_LEFT_ALT);
		TRANSLATE_KEY(GLFW_KEY_LEFT_SUPER);
		TRANSLATE_KEY(GLFW_KEY_RIGHT_SHIFT);
		TRANSLATE_KEY(GLFW_KEY_RIGHT_CONTROL);
		TRANSLATE_KEY(GLFW_KEY_RIGHT_ALT);
		TRANSLATE_KEY(GLFW_KEY_RIGHT_SUPER);
		TRANSLATE_KEY(GLFW_KEY_MENU);
		TRANSLATE_KEY(GLFW_KEY_LAST);
	}

#endif
}