#pragma once
#include "Core/Input/Key.h"
#include "Core/Input/Mods.h"
#include "Core/Input/MouseButton.h"

#ifdef DAT_DEBUG

#define TRANSLATE_MOUSE(buttonMacro) case buttonMacro: return #buttonMacro;

#define TRANSLATE_KEY(keyMacro) if (key == keyMacro) return #keyMacro;

namespace dat
{
	inline std::string debugMouseButtonName(MouseButton button)
	{
		switch (button)
		{
			TRANSLATE_MOUSE(MouseButton::MOUSE_BUTTON_UNKNOWN);
			TRANSLATE_MOUSE(MouseButton::MOUSE_BUTTON_LEFT);
			TRANSLATE_MOUSE(MouseButton::MOUSE_BUTTON_RIGHT);
			TRANSLATE_MOUSE(MouseButton::MOUSE_BUTTON_MIDDLE);
			TRANSLATE_MOUSE(MouseButton::MOUSE_BUTTON_4);
			TRANSLATE_MOUSE(MouseButton::MOUSE_BUTTON_5);
			TRANSLATE_MOUSE(MouseButton::MOUSE_BUTTON_6);
			TRANSLATE_MOUSE(MouseButton::MOUSE_BUTTON_LAST);
		}
	}

	inline std::string debugMods(Mods mods)
	{
		std::vector<std::string> modResults;

		if (mods & GLFW_MOD_SHIFT)
			modResults.push_back("SHIFT");

		if (mods & GLFW_MOD_CONTROL)
			modResults.push_back("CTRL");

		if (mods & GLFW_MOD_ALT)
			modResults.push_back("ALT");

		if (mods & GLFW_MOD_SUPER)
			modResults.push_back("SUPER");

		if (mods & GLFW_MOD_CAPS_LOCK)
			modResults.push_back("CAPS");

		if (mods & GLFW_MOD_NUM_LOCK)
			modResults.push_back("NUM_LOCK");

		if (modResults.size() == 0)
			return "NONE";

		if (modResults.size() == 1)
			return modResults.back().c_str();

		std::string str = "";
		for (size_t i = 0; i != modResults.size(); ++i)
		{
			if (i == modResults.size() - 1)
				str += modResults[i];
			else
				str += modResults[i] + " | ";
		}

		return str.c_str();
	}

	inline std::string debugKeyName(Key key)
	{
		TRANSLATE_KEY(Key::KEY_UNKNOWN);
		TRANSLATE_KEY(Key::KEY_SPACE);
		TRANSLATE_KEY(Key::KEY_APOSTROPHE);
		TRANSLATE_KEY(Key::KEY_COMMA);
		TRANSLATE_KEY(Key::KEY_MINUS);
		TRANSLATE_KEY(Key::KEY_PERIOD);
		TRANSLATE_KEY(Key::KEY_SLASH);
		TRANSLATE_KEY(Key::KEY_0);
		TRANSLATE_KEY(Key::KEY_1);
		TRANSLATE_KEY(Key::KEY_2);
		TRANSLATE_KEY(Key::KEY_3);
		TRANSLATE_KEY(Key::KEY_4);
		TRANSLATE_KEY(Key::KEY_5);
		TRANSLATE_KEY(Key::KEY_6);
		TRANSLATE_KEY(Key::KEY_7);
		TRANSLATE_KEY(Key::KEY_8);
		TRANSLATE_KEY(Key::KEY_9);
		TRANSLATE_KEY(Key::KEY_SEMICOLON);
		TRANSLATE_KEY(Key::KEY_EQUAL);
		TRANSLATE_KEY(Key::KEY_A);
		TRANSLATE_KEY(Key::KEY_B);
		TRANSLATE_KEY(Key::KEY_C);
		TRANSLATE_KEY(Key::KEY_D);
		TRANSLATE_KEY(Key::KEY_E);
		TRANSLATE_KEY(Key::KEY_F);
		TRANSLATE_KEY(Key::KEY_G);
		TRANSLATE_KEY(Key::KEY_H);
		TRANSLATE_KEY(Key::KEY_I);
		TRANSLATE_KEY(Key::KEY_J);
		TRANSLATE_KEY(Key::KEY_K);
		TRANSLATE_KEY(Key::KEY_L);
		TRANSLATE_KEY(Key::KEY_M);
		TRANSLATE_KEY(Key::KEY_N);
		TRANSLATE_KEY(Key::KEY_O);
		TRANSLATE_KEY(Key::KEY_P);
		TRANSLATE_KEY(Key::KEY_Q);
		TRANSLATE_KEY(Key::KEY_R);
		TRANSLATE_KEY(Key::KEY_S);
		TRANSLATE_KEY(Key::KEY_T);
		TRANSLATE_KEY(Key::KEY_U);
		TRANSLATE_KEY(Key::KEY_V);
		TRANSLATE_KEY(Key::KEY_W);
		TRANSLATE_KEY(Key::KEY_X);
		TRANSLATE_KEY(Key::KEY_Y);
		TRANSLATE_KEY(Key::KEY_Z);
		TRANSLATE_KEY(Key::KEY_LEFT_BRACKET);
		TRANSLATE_KEY(Key::KEY_BACKSLASH);
		TRANSLATE_KEY(Key::KEY_RIGHT_BRACKET);
		TRANSLATE_KEY(Key::KEY_GRAVE_ACCENT);
		TRANSLATE_KEY(Key::KEY_WORLD_1);
		TRANSLATE_KEY(Key::KEY_WORLD_2);
		TRANSLATE_KEY(Key::KEY_ESCAPE);
		TRANSLATE_KEY(Key::KEY_ENTER);
		TRANSLATE_KEY(Key::KEY_TAB);
		TRANSLATE_KEY(Key::KEY_BACKSPACE);
		TRANSLATE_KEY(Key::KEY_INSERT);
		TRANSLATE_KEY(Key::KEY_DELETE);
		TRANSLATE_KEY(Key::KEY_RIGHT);
		TRANSLATE_KEY(Key::KEY_LEFT);
		TRANSLATE_KEY(Key::KEY_DOWN);
		TRANSLATE_KEY(Key::KEY_UP);
		TRANSLATE_KEY(Key::KEY_PAGE_UP);
		TRANSLATE_KEY(Key::KEY_PAGE_DOWN);
		TRANSLATE_KEY(Key::KEY_HOME);
		TRANSLATE_KEY(Key::KEY_END);
		TRANSLATE_KEY(Key::KEY_CAPS_LOCK);
		TRANSLATE_KEY(Key::KEY_SCROLL_LOCK);
		TRANSLATE_KEY(Key::KEY_NUM_LOCK);
		TRANSLATE_KEY(Key::KEY_PRINT_SCREEN);
		TRANSLATE_KEY(Key::KEY_PAUSE);
		TRANSLATE_KEY(Key::KEY_F1);
		TRANSLATE_KEY(Key::KEY_F2);
		TRANSLATE_KEY(Key::KEY_F3);
		TRANSLATE_KEY(Key::KEY_F4);
		TRANSLATE_KEY(Key::KEY_F5);
		TRANSLATE_KEY(Key::KEY_F6);
		TRANSLATE_KEY(Key::KEY_F7);
		TRANSLATE_KEY(Key::KEY_F8);
		TRANSLATE_KEY(Key::KEY_F9);
		TRANSLATE_KEY(Key::KEY_F10);
		TRANSLATE_KEY(Key::KEY_F11);
		TRANSLATE_KEY(Key::KEY_F12);
		TRANSLATE_KEY(Key::KEY_F13);
		TRANSLATE_KEY(Key::KEY_F14);
		TRANSLATE_KEY(Key::KEY_F15);
		TRANSLATE_KEY(Key::KEY_F16);
		TRANSLATE_KEY(Key::KEY_F17);
		TRANSLATE_KEY(Key::KEY_F18);
		TRANSLATE_KEY(Key::KEY_F19);
		TRANSLATE_KEY(Key::KEY_F20);
		TRANSLATE_KEY(Key::KEY_F21);
		TRANSLATE_KEY(Key::KEY_F22);
		TRANSLATE_KEY(Key::KEY_F23);
		TRANSLATE_KEY(Key::KEY_F24);
		TRANSLATE_KEY(Key::KEY_F25);
		TRANSLATE_KEY(Key::KEY_KP_0);
		TRANSLATE_KEY(Key::KEY_KP_1);
		TRANSLATE_KEY(Key::KEY_KP_2);
		TRANSLATE_KEY(Key::KEY_KP_3);
		TRANSLATE_KEY(Key::KEY_KP_4);
		TRANSLATE_KEY(Key::KEY_KP_5);
		TRANSLATE_KEY(Key::KEY_KP_6);
		TRANSLATE_KEY(Key::KEY_KP_7);
		TRANSLATE_KEY(Key::KEY_KP_8);
		TRANSLATE_KEY(Key::KEY_KP_9);
		TRANSLATE_KEY(Key::KEY_KP_DECIMAL);
		TRANSLATE_KEY(Key::KEY_KP_DIVIDE);
		TRANSLATE_KEY(Key::KEY_KP_MULTIPLY);
		TRANSLATE_KEY(Key::KEY_KP_SUBTRACT);
		TRANSLATE_KEY(Key::KEY_KP_ADD);
		TRANSLATE_KEY(Key::KEY_KP_ENTER);
		TRANSLATE_KEY(Key::KEY_KP_EQUAL);
		TRANSLATE_KEY(Key::KEY_LEFT_SHIFT);
		TRANSLATE_KEY(Key::KEY_LEFT_CONTROL);
		TRANSLATE_KEY(Key::KEY_LEFT_ALT);
		TRANSLATE_KEY(Key::KEY_LEFT_SUPER);
		TRANSLATE_KEY(Key::KEY_RIGHT_SHIFT);
		TRANSLATE_KEY(Key::KEY_RIGHT_CONTROL);
		TRANSLATE_KEY(Key::KEY_RIGHT_ALT);
		TRANSLATE_KEY(Key::KEY_RIGHT_SUPER);
		TRANSLATE_KEY(Key::KEY_MENU);
		TRANSLATE_KEY(Key::KEY_LAST);
	}
}

#endif